### PR TITLE
Create Issue Template

### PR DESCRIPTION
**Pull request by jessicadaugherty**
Created an issue.md file for Issue Templates in pokt-network/pocket-operator

### CODE REVIEW

**Comment by Olshansk** [comment]
For context, we can probably copy-paste (with minorupdates) the templates from https://github.com/pokt-network/pocket/tree/main/.github

**Comment by jessicadaugherty** [comment]
> For context, we can probably copy-paste (with minorupdates) the templates from https://github.com/pokt-network/pocket/tree/main/.github

Thanks! Yup I just copied the same template from that repo. Lmk if you or @okdas want modifications before committing.

**Comment by jessicadaugherty** [comment]
@okdas do you mind if i merge this?

**Comment by okdas** [comment]
Hey @jessicadaugherty - thanks! I've changed some things as not everything from pocket repo applies here and made optional fields comments instead, so they're only visible during edit or creation.

**Comment by jessicadaugherty** [comment]
amazing! ty @okdas :)

**Pull request merged**
